spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  logging:
    level:
      com.results.central_results: INFO
      org.springframework.kafka: WARN
  cache:
    redis:
      time-to-live: 3600000 # 1 hora 